server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: clients_route
          uri: http://localhost:8080
          predicates:
            - Path=/clients/**
        - id: voitures_route
          uri: http://localhost:8089
          predicates:
            - Path=/voitures/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
